### ISSUE TITLE
Explain results output

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/Somatic-shortV-nf#12]
Would be helpful to users to understand what they can expect regarding the outputs of this pipeline. Suggesting we flesh out the results section of the `README.md` to include: 

* Description of output from each process 
* Description of final output that can be used for analysis and interpretation 
* Providing links to GATK documentation where relevant

**Comment by nandan75** [comment]
All good for this issue. Closing

**Comment by nandan75** [comment]
Closed
