### ISSUE TITLE
Clarify reference indexes needed

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/Somatic-shortV-nf#7]
What indexes are actually needed for the reference.fasta for the pipeline to function? 

Resolve [this conversation](https://github.com/Sydney-Informatics-Hub/Somatic-shortV-nf/pull/2#discussion_r1432015491) on #2

**Comment by nandan75** [comment]
I have now checked the documentations and also tested the pipeline by isolating the indices

Only the following reference files are used by gatk
Ref.fasta
Ref.fai and
Ref.dict 


I will update the README.md with this information when resolving some of the minor issues together
