### ISSUE TITLE
DRY out configurations

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/Somatic-shortV-nf#8]
A lot of repetition happening at the `withName{}` scope level inside `process{}` scopes in both the `nextflow.config` and the `gadi.config`. Settings that apply to all processes can be set before `withName{}` just under `process{`. For example you've set executor for each process separately in the `gadi.config`. 

Revisit Nextflow documentation re: process settings and DRY coding principles for guideance on how to make appropriate changes to your configs.

**Comment by nandan75** [comment]
The nextflow.config and config/gadi.config files are now updated as per DRY requirements.
None of the modules for Somatic variant calling  use native multithreading (mutect2 uses  scatter-garther).
I have included higher memory requirements for specific modules such as mutect and others in the config file. The higher memory is estimated based on the couple of runs peformed for FULL bam files.
