### ISSUE TITLE
Revise GATK best practices re: requirements for this pipeline 

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/Somatic-shortV-nf#9]
Revise the requirements for the pipeline to ensure your documentation is accurate and specific to this workflow. See comments on PR #2 related to indexing requirements, and bam-reference compatability where you've copied from GSV.

**Comment by nandan75** [comment]
The above requirements are now checked and resolved over the course of multiple corrections.
Closing this issue now
